[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
anchor_demo = "BUsJrPspUDhqt9ypTXTtRf67yXjvR3vq96p2QgTzBFav"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./test-ledger/validator-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
