[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = true

[programs.localnet]
anchor_demo = "F6DYjJGowRao4fxozyWLX329GPqzZSvaC4cxJNaQ9dWC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/hp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
